Use -Wno-ignored-qualified when we hit gcc bug 36052
git-svn-id: https://svn.dealii.org/trunk@16012 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -7303,6 +7303,86 @@ fi
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
 
+  case "$GXX_VERSION" in
+    gcc*)
+      { echo "$as_me:$LINENO: checking for warning bug with type qualifiers" >&5
+echo $ECHO_N "checking for warning bug with type qualifiers... $ECHO_C" >&6; }
+      ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+      CXXFLAGS="$CXXFLAGSG -Werror"
+      cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+          struct S {
+              typedef double value_type;
+          };
+
+          template <typename T> struct Traits {
+              typedef const typename T::value_type dereference_type;
+          };
+
+          template <class BlockVectorType> struct ConstIterator {
+              typedef typename Traits<BlockVectorType>::dereference_type dereference_type;
+
+              dereference_type operator * () const  { return 0; }
+          };
+
+          template class ConstIterator<S>;
+
+int
+main ()
+{
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+          { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+          { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+          CXXFLAGSG="$CXXFLAGSG -Wno-ignored-qualifiers"
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+    ;;
+  esac
+
+
   if test "x$GXX" = "xyes" ; then
     { echo "$as_me:$LINENO: checking for problem with -Wsynth and std::complex" >&5
 echo $ECHO_N "checking for problem with -Wsynth and std::complex... $ECHO_C" >&6; }
