error messages for borland and sun
git-svn-id: https://svn.dealii.org/trunk@9867 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -3386,6 +3386,15 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
           CXXFLAGSO="$CXXFLAGS -w"
           CXXFLAGSPIC="-KPIC"
           LDFLAGSPIC="-G"
+          { { echo "$as_me:$LINENO: error: Attention! deal.II is not known to work with SUN Compilers!
+	If you intend to port it" >&5
+echo "$as_me: error: Attention! deal.II is not known to work with SUN Compilers!
+	If you intend to port it" >&2;}
+   { (exit please remove this message
+	from aclocal.m4 and call autoconf and configure. If you do not understand
+	this); exit please remove this message
+	from aclocal.m4 and call autoconf and configure. If you do not understand
+	this; }; }
           ;;
 
       portland_group)
@@ -3412,6 +3421,15 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
           CXXFLAGSO="$CXXFLAGS -q -O2"
           CXXFLAGSPIC=""
           LDFLAGSPIC=""
+          { { echo "$as_me:$LINENO: error: Attention! deal.II is not known to work with Borland C++!
+	If you intend to port it to Borland C++" >&5
+echo "$as_me: error: Attention! deal.II is not known to work with Borland C++!
+	If you intend to port it to Borland C++" >&2;}
+   { (exit please remove this message
+	from aclocal.m4 and call autoconf and configure. If you do not understand
+	this); exit please remove this message
+	from aclocal.m4 and call autoconf and configure. If you do not understand
+	this; }; }
           ;;
 
       *)
