Fix two typos (using CFLAGSO when only CFLAGS is used). Also check whether we can switch off warning 1572 for the icc C compiler.
git-svn-id: https://svn.dealii.org/trunk@10806 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -3576,6 +3576,7 @@ echo "${ECHO_T}Unrecognized compiler -- still trying" >&6
   fi
 
 
+
     if test "$GCC" = yes ; then
     CFLAGS="$CFLAGS -O3 -funroll-loops -funroll-all-loops -fstrict-aliasing"
                     case "$target" in
@@ -3606,7 +3607,7 @@ echo "${ECHO_T}Unrecognized compiler -- still trying" >&6
           ;;
 
       MIPSpro*)
-          CFLAGSO="$CFLAGS -O2"
+          CFLAGS="$CFLAGS -O2"
           CFLAGSPIC="-KPIC"
           ;;
 
@@ -3622,10 +3623,60 @@ echo "${ECHO_T}Unrecognized compiler -- still trying" >&6
 
 	  	  	  case "$target" in
 	    *86*)
-		CFLAGSO="$CFLAGS -tpp6"
+		CFLAGS="$CFLAGS -tpp6"
 		;;
 	  esac
           ;;
+
+
+  echo "$as_me:$LINENO: checking whether -wd1572 is allowed for the C compiler" >&5
+echo $ECHO_N "checking whether -wd1572 is allowed for the C compiler... $ECHO_C" >&6
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+  CFLAGS="$CFLAGS -wd1572"
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	CFLAGS="$CFLAGS -wd1572"
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
 
       *)
           echo "$as_me:$LINENO: result: Unknown C compiler - using generic options" >&5
