More configure changes.
git-svn-id: https://svn.dealii.org/trunk@3054 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# From configure.in Revision: 1.25 
+# From configure.in Revision: 1.26 
 
 
 
@@ -1388,22 +1388,29 @@ if test "${with_kdoc+set}" = set; then
   withval="$with_kdoc"
   kdocdir=$withval
 else
-  kdocdir=${DEAL2_DIR}/doc/auto/scripts/kdoc
+  kdocdir=${DEAL2_DIR}/contrib/kdoc/bin
 fi
 
 echo $ac_n "checking for kdoc""... $ac_c" 1>&6
 echo "configure:1396: checking for kdoc" >&5
-if test -r $kdocdir/kdoc ; then
-  echo "$ac_t""found" 1>&6
+if test $kdocdir != ${DEAL2_DIR}/contrib/kdoc/bin ; then
+  if test -r $kdocdir/kdoc ; then
+    echo "$ac_t""found" 1>&6
+  else
+    echo "$ac_t""not found" 1>&6
+    { echo "configure: error: Invalid kdoc path $kdocdir/kdoc" 1>&2; exit 1; }
+  fi
+
+  if test -r $kdocdir/Version ; then
+    kdocversion=`cat $kdocdir/Version` ;
+  else
+    kdocversion=1;
+  fi
 else
-  echo "$ac_t""not found" 1>&6
-  { echo "configure: error: Invalid kdoc path" 1>&2; exit 1; }
+  kdocversion=`cat ${DEAL2_DIR}/contrib/kdoc/src/Version`
+  echo "$ac_t""using default version $kdocversion" 1>&6
 fi
-if test -r $kdocdir/Version ; then
-  kdocversion=`cat $kdocdir/Version` ;
-else
-  kdocversion=1;
-fi
+
 
 
 
@@ -1421,7 +1428,7 @@ if test "$docxx" = to-be-determined ; then
   # Extract the first word of ""doc++"", so it can be a program name with args.
 set dummy "doc++"; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1425: checking for $ac_word" >&5
+echo "configure:1432: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_docxx'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1455,7 +1462,7 @@ fi
 
 else
   echo $ac_n "checking for doc++""... $ac_c" 1>&6
-echo "configure:1459: checking for doc++" >&5
+echo "configure:1466: checking for doc++" >&5
   if test -x "$docxx" ; then
     echo "$ac_t""yes" 1>&6
   else
@@ -1470,7 +1477,7 @@ fi
 
 
   echo $ac_n "checking whether getrusage is properly declared""... $ac_c" 1>&6
-echo "configure:1474: checking whether getrusage is properly declared" >&5
+echo "configure:1481: checking whether getrusage is properly declared" >&5
   ac_ext=C
 # CXXFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -1480,7 +1487,7 @@ cross_compiling=$ac_cv_prog_cxx_cross
 
 
   cat > conftest.$ac_ext <<EOF
-#line 1484 "configure"
+#line 1491 "configure"
 #include "confdefs.h"
 
 #include <sys/resource.h>
@@ -1492,7 +1499,7 @@ int main() {
     
 ; return 0; }
 EOF
-if { (eval echo configure:1496: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1503: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   
 	echo "$ac_t"""yes"" 1>&6
@@ -1524,17 +1531,17 @@ esac
 
 
 echo $ac_n "checking for consistency of CXXFLAGSG flags""... $ac_c" 1>&6
-echo "configure:1528: checking for consistency of CXXFLAGSG flags" >&5
+echo "configure:1535: checking for consistency of CXXFLAGSG flags" >&5
 CXXFLAGS="$CXXFLAGSG"
 cat > conftest.$ac_ext <<EOF
-#line 1531 "configure"
+#line 1538 "configure"
 #include "confdefs.h"
 
 int main() {
 ;
 ; return 0; }
 EOF
-if { (eval echo configure:1538: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1545: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   
     echo "$ac_t""yes" 1>&6
@@ -1551,17 +1558,17 @@ fi
 rm -f conftest*
 
 echo $ac_n "checking for consistency of CXXFLAGSO flags""... $ac_c" 1>&6
-echo "configure:1555: checking for consistency of CXXFLAGSO flags" >&5
+echo "configure:1562: checking for consistency of CXXFLAGSO flags" >&5
 CXXFLAGS="$CXXFLAGSO"
 cat > conftest.$ac_ext <<EOF
-#line 1558 "configure"
+#line 1565 "configure"
 #include "confdefs.h"
 
 int main() {
 ;
 ; return 0; }
 EOF
-if { (eval echo configure:1565: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1572: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   
     echo "$ac_t""yes" 1>&6
