Regenerate.
git-svn-id: https://svn.dealii.org/trunk@6102 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -2602,7 +2602,9 @@ echo "${ECHO_T}C++ compiler is gcc-2.95" >&6
       *2.96*)
   	echo "$as_me:$LINENO: result: C++ compiler is gcc-2.96" >&5
 echo "${ECHO_T}C++ compiler is gcc-2.96" >&6
-  	GXX_VERSION=gcc2.96
+  				{ { echo "$as_me:$LINENO: error: gcc 2.96 is not supported. Please read the deal.II FAQs." >&5
+echo "$as_me: error: gcc 2.96 is not supported. Please read the deal.II FAQs." >&2;}
+   { (exit 1); exit 1; }; }
   	;;
       *2.97*)
   	echo "$as_me:$LINENO: result: C++ compiler is gcc-2.97" >&5
@@ -2688,7 +2690,7 @@ echo "${ECHO_T}C++ compiler is Sun Forte compiler" >&6
                   GXX_VERSION=sun_forte
                 else
 
-  	            	          is_kai_cc="`($CXX -V 2>&1) | grep 'KAI C++'`"
+  	            	          is_kai_cc="`($CXX --version 2>&1) | grep 'KAI C++'`"
   	          if test "x$is_kai_cc" != "x" ; then
   	            echo "$as_me:$LINENO: result: C++ compiler is KAI C++" >&5
 echo "${ECHO_T}C++ compiler is KAI C++" >&6
@@ -2889,9 +2891,15 @@ rm -f conftest.$ac_objext conftest.$ac_ext
 
       portland_group)
 	            	   	  	                                                     	  	  	  CXXFLAGSG="$CXXFLAGS -DDEBUG -g --display_error_number --diag_suppress 111 --diag_suppress 177 --diag_suppress 175"
-          CXXFLAGSO="$CXXFLAGS -tused -fast -O2"
+          CXXFLAGSO="$CXXFLAGS -fast -O2 --display_error_number --diag_suppress 111 --diag_suppress 177 --diag_suppress 175"
           CXXFLAGSPIC="-Kpic"
           ;;
+
+      kai_cc)
+          CXXFLAGSG="$CXXFLAGS --strict -D__KAI_STRICT --max_pending_instantiations 32 --display_error_number -g +K0 --no_implicit_typename"
+          CXXFLAGSO="$CXXFLAGS +K3 -O2 --abstract_float --abstract_pointer -w --display_error_number --max_pending_instantiations 32 --display_error_number"
+          CXXFLAGSPIC="-fPIC"
+	  ;;
 
       hp_aCC)
 	  	            CXXFLAGSG="$CXXFLAGS -g1 +p +w -z -Aa -AA"
@@ -5466,7 +5474,7 @@ int
 main ()
 {
 
-int seed = 0;
+unsigned int seed = 0;
 int i=rand_r(&i);
 
   ;
