Support PETSc 2.3.0
git-svn-id: https://svn.dealii.org/trunk@10849 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -9083,73 +9083,6 @@ _ACEOF
 
     if test "$USE_CONTRIB_PETSC" = "yes" ; then
 
-  echo "$as_me:$LINENO: checking for PETSc library architecture" >&5
-echo $ECHO_N "checking for PETSc library architecture... $ECHO_C" >&6
-
-
-# Check whether --with-petsc-arch or --without-petsc-arch was given.
-if test "${with_petsc_arch+set}" = set; then
-  withval="$with_petsc_arch"
-
-        DEAL_II_PETSC_ARCH=$withval
-	echo "$as_me:$LINENO: result: $DEAL_II_PETSC_ARCH" >&5
-echo "${ECHO_T}$DEAL_II_PETSC_ARCH" >&6
-
-                if test ! -d $DEAL_II_PETSC_DIR/lib/libg_c++/$DEAL_II_PETSC_ARCH \
-             ; then
-          	            if test -d $DEAL_II_PETSC_DIR/lib/libg/$DEAL_II_PETSC_ARCH \
-             ; then
-            { { echo "$as_me:$LINENO: error: PETSc has not been compiled for C++, but
-                          deal.II needs this" >&5
-echo "$as_me: error: PETSc has not been compiled for C++, but
-                          deal.II needs this" >&2;}
-   { (exit 1); exit 1; }; }
-          else
-            { { echo "$as_me:$LINENO: error: PETSc has not been compiled for the architecture
-                          specified with --with-petsc-arch" >&5
-echo "$as_me: error: PETSc has not been compiled for the architecture
-                          specified with --with-petsc-arch" >&2;}
-   { (exit 1); exit 1; }; }
-          fi
-	fi
-
-else
-
-                if test "x$PETSC_ARCH" != "x" ; then
-          DEAL_II_PETSC_ARCH="$PETSC_ARCH"
-	  echo "$as_me:$LINENO: result: $DEAL_II_PETSC_ARCH" >&5
-echo "${ECHO_T}$DEAL_II_PETSC_ARCH" >&6
-
-                    if test ! -d $DEAL_II_PETSC_DIR/lib/libg_c++/$DEAL_II_PETSC_ARCH \
-             ; then
-            	                if test -d $DEAL_II_PETSC_DIR/lib/libg/$DEAL_II_PETSC_ARCH \
-               ; then
-              { { echo "$as_me:$LINENO: error: PETSc has not been compiled for C++, but
-                            deal.II needs this" >&5
-echo "$as_me: error: PETSc has not been compiled for C++, but
-                            deal.II needs this" >&2;}
-   { (exit 1); exit 1; }; }
-            else
-              { { echo "$as_me:$LINENO: error: PETSc has not been compiled for the architecture
-                            specified with --with-petsc-arch" >&5
-echo "$as_me: error: PETSc has not been compiled for the architecture
-                            specified with --with-petsc-arch" >&2;}
-   { (exit 1); exit 1; }; }
-            fi
-          fi
-        else
-    	  { { echo "$as_me:$LINENO: error: If PETSc is used, you must specify the architecture
-                        either through the PETSC_ARCH environment variable,
-                        or through the --with-petsc-arch flag" >&5
-echo "$as_me: error: If PETSc is used, you must specify the architecture
-                        either through the PETSC_ARCH environment variable,
-                        or through the --with-petsc-arch flag" >&2;}
-   { (exit 1); exit 1; }; }
-        fi
-
-fi;
-
-
   echo "$as_me:$LINENO: checking for PETSc version" >&5
 echo $ECHO_N "checking for PETSc version... $ECHO_C" >&6
 
@@ -9165,6 +9098,79 @@ echo $ECHO_N "checking for PETSc version... $ECHO_C" >&6
   PETSC_VERSION="$DEAL_II_PETSC_VERSION_MAJOR.$DEAL_II_PETSC_VERSION_MINOR.$DEAL_II_PETSC_VERSION_SUBMINOR"
   echo "$as_me:$LINENO: result: $PETSC_VERSION" >&5
 echo "${ECHO_T}$PETSC_VERSION" >&6
+
+
+  echo "$as_me:$LINENO: checking for PETSc library architecture" >&5
+echo $ECHO_N "checking for PETSc library architecture... $ECHO_C" >&6
+
+
+# Check whether --with-petsc-arch or --without-petsc-arch was given.
+if test "${with_petsc_arch+set}" = set; then
+  withval="$with_petsc_arch"
+
+        DEAL_II_PETSC_ARCH=$withval
+	echo "$as_me:$LINENO: result: $DEAL_II_PETSC_ARCH" >&5
+echo "${ECHO_T}$DEAL_II_PETSC_ARCH" >&6
+
+else
+
+                if test "x$PETSC_ARCH" != "x" ; then
+          DEAL_II_PETSC_ARCH="$PETSC_ARCH"
+	  echo "$as_me:$LINENO: result: $DEAL_II_PETSC_ARCH" >&5
+echo "${ECHO_T}$DEAL_II_PETSC_ARCH" >&6
+        else
+    	  { { echo "$as_me:$LINENO: error: If PETSc is used, you must specify the architecture
+                        either through the PETSC_ARCH environment variable,
+                        or through the --with-petsc-arch flag" >&5
+echo "$as_me: error: If PETSc is used, you must specify the architecture
+                        either through the PETSC_ARCH environment variable,
+                        or through the --with-petsc-arch flag" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+
+fi;
+
+
+  if test "x$PETSC_ARCH" != "x" ; then
+                case "${DEAL_II_PETSC_VERSION_MAJOR}.${DEAL_II_PETSC_VERSION_MINOR}.${DEAL_II_PETSC_VERSION_SUBMINOR}" in
+      2.2*)
+        if test ! -d $DEAL_II_PETSC_DIR/lib/libg_c++/$DEAL_II_PETSC_ARCH \
+             ; then
+                              if test -d $DEAL_II_PETSC_DIR/lib/libg/$DEAL_II_PETSC_ARCH \
+             ; then
+            { { echo "$as_me:$LINENO: error: PETSc has not been compiled for C++, but
+                          deal.II needs this" >&5
+echo "$as_me: error: PETSc has not been compiled for C++, but
+                          deal.II needs this" >&2;}
+   { (exit 1); exit 1; }; }
+          else
+            { { echo "$as_me:$LINENO: error: PETSc has not been compiled for the architecture
+                          specified with --with-petsc-arch" >&5
+echo "$as_me: error: PETSc has not been compiled for the architecture
+                          specified with --with-petsc-arch" >&2;}
+   { (exit 1); exit 1; }; }
+          fi
+        fi
+        ;;
+
+      2.3*)
+        if test ! -d $DEAL_II_PETSC_DIR/lib/$DEAL_II_PETSC_ARCH \
+             ; then
+          { { echo "$as_me:$LINENO: error: PETSc has not been compiled for the architecture
+                        specified with --with-petsc-arch" >&5
+echo "$as_me: error: PETSc has not been compiled for the architecture
+                        specified with --with-petsc-arch" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+        ;;
+
+      *)
+        { { echo "$as_me:$LINENO: error: Unknown PETSc version" >&5
+echo "$as_me: error: Unknown PETSc version" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+    esac
+  fi
 
 
         if test "x$with_petsc" = "x" ; then
@@ -9195,9 +9201,6 @@ if test "x$with_lapack" != "x" ; then
   fi
 fi
 
-
-echo $with_petsc
-echo $enableshared
 
 if test "x$with_petsc" != "x" ; then
   if test "x$enableshared" = "xno" ; then
