.
git-svn-id: https://svn.dealii.org/trunk@6946 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -3342,6 +3342,71 @@ echo "$as_me: error: No threading compiler options for this C++ compiler
   fi
 
 
+  if test "$enablemultithreading" = yes ; then
+    case "$GXX_VERSION" in
+      gcc*)
+  	echo "$as_me:$LINENO: checking for only partly bracketed mutex initializer" >&5
+echo $ECHO_N "checking for only partly bracketed mutex initializer... $ECHO_C" >&6
+	CXXFLAGS="$CXXFLAGSG -Werror"
+	ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#	include <vector>
+
+int
+main ()
+{
+;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+	  echo "$as_me:$LINENO: result: not necessary" >&5
+echo "${ECHO_T}not necessary" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+	  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	  CXXFLAGSG="$CXXFLAGSG -Wno-missing-braces"
+	  CXXFLAGSO="$CXXFLAGSO -Wno-missing-braces"
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+	;;
+      *)
+        ;;
+    esac
+  fi
+
+
 
 
 
