change NetCDF configuration
git-svn-id: https://svn.dealii.org/trunk@12754 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -11027,9 +11027,6 @@ _ACEOF
 
 
 
-  echo "$as_me:$LINENO: checking for NetCDF library directory" >&5
-echo $ECHO_N "checking for NetCDF library directory... $ECHO_C" >&6
-
 
 # Check whether --with-netcdf or --without-netcdf was given.
 if test "${with_netcdf+set}" = set; then
@@ -11043,95 +11040,288 @@ else
   	  DEAL_II_NETCDF_DIR="$NETCDF_DIR"
         else
 	  DEAL_II_NETCDF_DIR=""
-          echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6
         fi
 
 fi;
 
   if test "x$DEAL_II_NETCDF_DIR" != "x" ; then
-    echo "$as_me:$LINENO: result: $DEAL_II_NETCDF_DIR" >&5
-echo "${ECHO_T}$DEAL_II_NETCDF_DIR" >&6
-    as_ac_File=`echo "ac_cv_file_$DEAL_II_NETCDF_DIR/lib/libnetcdf.a" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $DEAL_II_NETCDF_DIR/lib/libnetcdf.a" >&5
-echo $ECHO_N "checking for $DEAL_II_NETCDF_DIR/lib/libnetcdf.a... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
+    CPPFLAGS="-I$DEAL_II_NETCDF_DIR/include $CPPFLAGS"
+    LDFLAGS="-L$DEAL_II_NETCDF_DIR/lib $LDFLAGS"
+    if test "$LD_PATH_OPTION" != "no" ; then
+      LDFLAGS="$LD_PATH_OPTION$DEAL_II_NETCDF_DIR/lib $LDFLAGS"
+    fi
+  fi
+
+          if test "${ac_cv_header_netcdfcpp_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for netcdfcpp.h" >&5
+echo $ECHO_N "checking for netcdfcpp.h... $ECHO_C" >&6
+if test "${ac_cv_header_netcdfcpp_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_netcdfcpp_h" >&5
+echo "${ECHO_T}$ac_cv_header_netcdfcpp_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking netcdfcpp.h usability" >&5
+echo $ECHO_N "checking netcdfcpp.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <netcdfcpp.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking netcdfcpp.h presence" >&5
+echo $ECHO_N "checking netcdfcpp.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <netcdfcpp.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: netcdfcpp.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: netcdfcpp.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netcdfcpp.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: netcdfcpp.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: netcdfcpp.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: netcdfcpp.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netcdfcpp.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: netcdfcpp.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netcdfcpp.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: netcdfcpp.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netcdfcpp.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: netcdfcpp.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netcdfcpp.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: netcdfcpp.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: netcdfcpp.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: netcdfcpp.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## -------------------------------- ##
+## Report this to dealii@dealii.org ##
+## -------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for netcdfcpp.h" >&5
+echo $ECHO_N "checking for netcdfcpp.h... $ECHO_C" >&6
+if test "${ac_cv_header_netcdfcpp_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$DEAL_II_NETCDF_DIR/lib/libnetcdf.a"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
+  ac_cv_header_netcdfcpp_h=$ac_header_preproc
 fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-  NETCDF_LIB=$DEAL_II_NETCDF_DIR/lib/libnetcdf.a
-fi
+echo "$as_me:$LINENO: result: $ac_cv_header_netcdfcpp_h" >&5
+echo "${ECHO_T}$ac_cv_header_netcdfcpp_h" >&6
 
-    as_ac_File=`echo "ac_cv_file_$DEAL_II_NETCDF_DIR/lib/libnetcdf_c++.a" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $DEAL_II_NETCDF_DIR/lib/libnetcdf_c++.a" >&5
-echo $ECHO_N "checking for $DEAL_II_NETCDF_DIR/lib/libnetcdf_c++.a... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
+fi
+if test $ac_cv_header_netcdfcpp_h = yes; then
+
+echo "$as_me:$LINENO: checking for nc_open in -lnetcdf" >&5
+echo $ECHO_N "checking for nc_open in -lnetcdf... $ECHO_C" >&6
+if test "${ac_cv_lib_netcdf_nc_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$DEAL_II_NETCDF_DIR/lib/libnetcdf_c++.a"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
-fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-  NETCDF_LIB="$DEAL_II_NETCDF_DIR/lib/libnetcdf_c++.a $NETCDF_LIB"
-else
-  NETCDF_LIB=""
-fi
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lnetcdf  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
-    as_ac_File=`echo "ac_cv_file_$DEAL_II_NETCDF_DIR/include/netcdfcpp.h" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $DEAL_II_NETCDF_DIR/include/netcdfcpp.h" >&5
-echo $ECHO_N "checking for $DEAL_II_NETCDF_DIR/include/netcdfcpp.h... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char nc_open ();
+int
+main ()
+{
+nc_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_netcdf_nc_open=yes
 else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$DEAL_II_NETCDF_DIR/include/netcdfcpp.h"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
-fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-  NETCDF_INCLUDE_DIR=-I$DEAL_II_NETCDF_DIR/include
-else
-  NETCDF_LIB=""
-fi
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
-
-    if (test "x$NETCDF_LIB" != "x") ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define DEAL_II_HAVE_NETCDF 1
+ac_cv_lib_netcdf_nc_open=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_netcdf_nc_open" >&5
+echo "${ECHO_T}$ac_cv_lib_netcdf_nc_open" >&6
+if test $ac_cv_lib_netcdf_nc_open = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBNETCDF 1
 _ACEOF
 
+  LIBS="-lnetcdf $LIBS"
 
-      LIBS="$NETCDF_LIB $LIBS"
-    fi
+fi
+
+fi
+
+
+
+      if test "x$HAVE_LIBNETCDF" == "x1" ; then
+    LIBS="-lnetcdf_c++ $LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+  /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <netcdfcpp.h>
+
+int
+main ()
+{
+NcFile test("test")
+  ;
+  return 0;
+}
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+{ { echo "$as_me:$LINENO: error: Your NetCDF installation is incomplete: C++ library missing
+See \`config.log' for more details." >&5
+echo "$as_me: error: Your NetCDF installation is incomplete: C++ library missing
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
   fi
 
 
