Detect and work around a bug in an old version of gcc.
git-svn-id: https://svn.dealii.org/trunk@8137 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -5106,6 +5106,69 @@ fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 
 
+  echo "$as_me:$LINENO: checking for array assignment in conditional bug" >&5
+echo $ECHO_N "checking for array assignment in conditional bug... $ECHO_C" >&6
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  CXXFLAGS="-W -Wall -Werror"
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+
+  const int x[2][2] = {{1,1},{1,1}};
+  const int (&y)[2] = (1 ? x[0] : x[1]);
+  return y[0];
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+      echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define DEAL_II_ARRAY_CONDITIONAL_DECAY_BUG 1
+_ACEOF
+
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+
   if test "x$GXX_VERSION" != "x" ; then
     echo "$as_me:$LINENO: checking for boost::shared_ptr assignment operator= template buglet" >&5
 echo $ECHO_N "checking for boost::shared_ptr assignment operator= template buglet... $ECHO_C" >&6
