Check for a compiler bug on Mac OS X.
git-svn-id: https://svn.dealii.org/trunk@19414 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -8163,6 +8163,89 @@ fi
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
 
+  if test "x$GXX" = "xyes" ; then
+    { echo "$as_me:$LINENO: checking for boost::bind compiler internal error" >&5
+echo $ECHO_N "checking for boost::bind compiler internal error... $ECHO_C" >&6; }
+    ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    CXXFLAGS="$CXXFLAGSG -I./contrib/boost/include"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <complex>
+#include <iostream>
+#include <boost/bind.hpp>
+
+template<typename number>
+void bug_function (number test)
+{
+  std::cout << test << std::endl;
+}
+
+int
+main ()
+{
+
+  std::complex<double> double_val (1., 2.);
+  boost::bind(&bug_function<std::complex<double> >,
+	      double_val)();
+
+  std::complex<float> float_val (1., 2.);
+  boost::bind(&bug_function<std::complex<float> >,
+	      float_val)();
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+        { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define DEAL_II_BOOST_BIND_COMPILER_BUG 1
+_ACEOF
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+  fi
+
+
   { echo "$as_me:$LINENO: checking for const member deduction bug" >&5
 echo $ECHO_N "checking for const member deduction bug... $ECHO_C" >&6; }
   ac_ext=cpp
