Detect Trilinos. Don't do anything with it right now.
git-svn-id: https://svn.dealii.org/trunk@15615 0785d39b-7218-0410-832d-ea1e28bc413d

diff --git a/deal.II/configure b/deal.II/configure
--- a/deal.II/configure
+++ b/deal.II/configure
@@ -715,6 +715,10 @@ DEAL_II_PETSC_VERSION_MINOR
 DEAL_II_PETSC_VERSION_SUBMINOR
 DEAL_II_PETSC_MPIUNI_LIB
 DEAL_II_DEFINE_DEAL_II_USE_PETSC
+USE_CONTRIB_TRILINOS
+DEAL_II_TRILINOS_DIR
+DEAL_II_TRILINOS_SHARED
+DEAL_II_TRILINOS_STATIC
 NEEDS_F77LIBS
 HSL_INCLUDE_DIR
 USE_CONTRIB_HSL
@@ -1345,6 +1349,10 @@ Optional Packages:
   --with-petsc-arch=architecture  Specify the architecture for your PETSc
                           installation; use this if you want to override
                           the PETSC_ARCH environment variable.
+  --with-trilinos=/path/to/trilinos  Specify the path to the Trilinos installation,
+                          of which the include and lib directories
+                          are subdirs; use this if you want to override
+                          the TRILINOS_DIR environment variable.
   --with-blas=blaslib     use the blas library blaslib. Make sure
                           the path to the libary is searched by ld, since
                           it is included by the argument -lblaslib. If no
@@ -11311,7 +11319,6 @@ echo "${ECHO_T}---------------- configuring additional libs ----------------" >&
 
 
 
-
     { echo "$as_me:$LINENO: checking for PETSc library directory" >&5
 echo $ECHO_N "checking for PETSc library directory... $ECHO_C" >&6; }
 
@@ -11507,6 +11514,113 @@ echo "${ECHO_T}$DEAL_II_PETSC_MPIUNI_LIB" >&6; }
 
 
 
+  { echo "$as_me:$LINENO: checking for Trilinos library directory" >&5
+echo $ECHO_N "checking for Trilinos library directory... $ECHO_C" >&6; }
+
+
+# Check whether --with-trilinos was given.
+if test "${with_trilinos+set}" = set; then
+  withval=$with_trilinos;
+                if test "x$withval" = "xno" ; then
+          { echo "$as_me:$LINENO: result: explicitly disabled" >&5
+echo "${ECHO_T}explicitly disabled" >&6; }
+          USE_CONTRIB_TRILINOS=no
+        else
+	  USE_CONTRIB_TRILINOS=yes
+          DEAL_II_TRILINOS_DIR=$withval
+	  { echo "$as_me:$LINENO: result: $DEAL_II_TRILINOS_DIR" >&5
+echo "${ECHO_T}$DEAL_II_TRILINOS_DIR" >&6; }
+
+                    if test ! -d $DEAL_II_TRILINOS_DIR/include \
+               -o ! -d $DEAL_II_TRILINOS_DIR/lib ; then
+            { { echo "$as_me:$LINENO: error: Path to Trilinos specified with --with-trilinos does not
+ 		  	  point to a complete Trilinos installation" >&5
+echo "$as_me: error: Path to Trilinos specified with --with-trilinos does not
+ 		  	  point to a complete Trilinos installation" >&2;}
+   { (exit 1); exit 1; }; }
+	  fi
+        fi
+
+else
+
+                if test "x$TRILINOS_DIR" != "x" ; then
+  	  USE_CONTRIB_TRILINOS=yes
+          DEAL_II_TRILINOS_DIR="$TRILINOS_DIR"
+	  { echo "$as_me:$LINENO: result: $DEAL_II_TRILINOS_DIR" >&5
+echo "${ECHO_T}$DEAL_II_TRILINOS_DIR" >&6; }
+
+                    if test ! -d $DEAL_II_TRILINOS_DIR/include \
+               -o ! -d $DEAL_II_TRILINOS_DIR/lib ; then
+            { { echo "$as_me:$LINENO: error: The path to Trilinos specified in the TRILINOS_DIR
+	  		  environment variable does not
+ 			  point to a complete Trilinos installation" >&5
+echo "$as_me: error: The path to Trilinos specified in the TRILINOS_DIR
+	  		  environment variable does not
+ 			  point to a complete Trilinos installation" >&2;}
+   { (exit 1); exit 1; }; }
+	  fi
+        else
+	  USE_CONTRIB_TRILINOS=no
+          DEAL_II_TRILINOS_DIR=""
+          { echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6; }
+        fi
+
+fi
+
+
+    if test "$USE_CONTRIB_TRILINOS" = "yes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define DEAL_II_USE_TRILINOS 1
+_ACEOF
+
+
+                        DEAL_II_DEFINE_DEAL_II_USE_TRILINOS=DEAL_II_USE_TRILINOS
+
+
+
+  { echo "$as_me:$LINENO: checking whether Trilinos uses shared libraries" >&5
+echo $ECHO_N "checking whether Trilinos uses shared libraries... $ECHO_C" >&6; }
+  if test -f $DEAL_II_TRILINOS_DIR/lib/libepetra${shared_lib_suffix} ; then
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+    DEAL_II_TRILINOS_SHARED=yes
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+  fi
+
+  { echo "$as_me:$LINENO: checking whether Trilinos uses static libraries" >&5
+echo $ECHO_N "checking whether Trilinos uses static libraries... $ECHO_C" >&6; }
+  if test -f $DEAL_II_TRILINOS_DIR/lib/libepetra${static_lib_suffix} ; then
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+    DEAL_II_TRILINOS_STATIC=yes
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+  fi
+
+    if test "x${DEAL_II_TRILINOS_SHARED}${DEAL_II_TRILINOS_STATIC}" = "x" ; then
+    { { echo "$as_me:$LINENO: error: Unable to determine whether Trilinos uses shared or
+                  static libraries." >&5
+echo "$as_me: error: Unable to determine whether Trilinos uses shared or
+                  static libraries." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+        if test "x$with_trilinos" = "x" ; then
+      with_trilinos="yes"
+    fi
+  fi
+
+
+
+
+
+
 
 
 if test "x$with_umfpack" != "x" -a "x$with_umfpack" != "xno" ; then
@@ -11615,7 +11729,8 @@ echo "${ECHO_T}$ac_res" >&6; }
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
 
                      LIBS="-l$blas $LIBS"
-                     cat >>confdefs.h <<\_ACEOF
+
+cat >>confdefs.h <<\_ACEOF
 #define HAVE_LIBBLAS 1
 _ACEOF
 
@@ -11814,7 +11929,8 @@ echo "${ECHO_T}$ac_res" >&6; }
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
 
                        LIBS="-l$blas $LIBS"
-                       cat >>confdefs.h <<\_ACEOF
+
+cat >>confdefs.h <<\_ACEOF
 #define HAVE_LIBBLAS 1
 _ACEOF
 
@@ -12726,7 +12842,8 @@ ac_res=`eval echo '${'$as_ac_Lib'}'`
 echo "${ECHO_T}$ac_res" >&6; }
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
    LIBS="-l$lapack $LIBS"
-        cat >>confdefs.h <<\_ACEOF
+
+cat >>confdefs.h <<\_ACEOF
 #define HAVE_LIBLAPACK 1
 _ACEOF
 
@@ -14130,6 +14247,10 @@ for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
 DEAL_II_PETSC_MPIUNI_LIB!$DEAL_II_PETSC_MPIUNI_LIB$ac_delim
 DEAL_II_DEFINE_DEAL_II_USE_PETSC!$DEAL_II_DEFINE_DEAL_II_USE_PETSC$ac_delim
+USE_CONTRIB_TRILINOS!$USE_CONTRIB_TRILINOS$ac_delim
+DEAL_II_TRILINOS_DIR!$DEAL_II_TRILINOS_DIR$ac_delim
+DEAL_II_TRILINOS_SHARED!$DEAL_II_TRILINOS_SHARED$ac_delim
+DEAL_II_TRILINOS_STATIC!$DEAL_II_TRILINOS_STATIC$ac_delim
 NEEDS_F77LIBS!$NEEDS_F77LIBS$ac_delim
 HSL_INCLUDE_DIR!$HSL_INCLUDE_DIR$ac_delim
 USE_CONTRIB_HSL!$USE_CONTRIB_HSL$ac_delim
@@ -14150,7 +14271,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 24; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
